export const black = '#000'
export const gray = '#757575'
export const white = '#fff'
export const red = '#b71845'
export const charcoal = '#333'
export const halfGray = '#666'
export const lightGray = '#ccc'
